a_male_1_blog/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import path, include

from blog.sitemaps import PostSitemap


sitemaps = {'posts': PostSitemap}


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemaps.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap')
]

blog/urls.py
from django.urls import path

from . import views
from .feeds import LatesPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.PostListView.as_view(), name='post_list_cbv'),
    path('function-views/', views.post_list, name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('feed/', LatesPostsFeed(), name='post_feed'),
    path('search/', views.post_search_simple, name='post_search'),
    path('search-rank/', views.post_search_rank, name='post_search_rank'),
    path('search-weight/', views.post_search_weight, name='post_search_weight'),
    path('search-trigram-similarity/', views.post_search_trigram_similarity,
         name='post_search_trigram_similarity'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils import timezone

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager()  # Менеджер по умолчанию.
    published = PublishedManager()  # Наш новый менеджер.
    # Позволяет добавлять, получать список и удалять теги для объектов статей.
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self) -> str:
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                 self.publish.month,
                                                 self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self) -> str:
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms

from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, \
    SearchRank, TrigramSimilarity
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.db.models import Count
from django.views.generic import ListView
from django.shortcuts import render, get_object_or_404

from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm


def post_list(request, tag_slug=None):
    """ Выводим все опубликованные статьи. """
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # По 3 статьи на каждой странице
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, возвращаем первую страницу.
        posts = paginator.page(1)
    except EmptyPage:
        # Если номер страницы больше, чем общее кол-во страниц,
        # возвращаем последнюю страницу.
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag': tag})


def post_detail(request, year, month, day, post):
    """ Выводим подробную информацию о статье. """
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year, publish__month=month,
                             publish__day=day)
    # Список активных комментариев для данной статьи
    comments = Comment.objects.filter(active=True)
    new_comment = None

    # Добавил по причине "local variable 'comment_form'
    # referenced before assignment"
    comment_form = CommentForm()
    if request.method == 'POST':
        # Пользователь отправил комментарий.
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Создаем комментарий, но пока не сохраняем в базе данных.
            new_comment = comment_form.save(commit=False)
            # Привязываем комментарий к текущей статье
            new_comment.post = post
            # Сохраняем комментарий в базе данных
            new_comment.save()
        else:
            comment_form = CommentForm()

    # Формирование списка похожих статей
    # Метод QuerySet’а values_list() воз-
    # вращает кортежи со значениями заданного поля. Мы указали flat=True,
    # чтобы получить «плоский» список вида [1, 2, 3, ...]
    post_tags_ids = post.tags.values_list('id', flat=True)
    # использует функцию агрегации Count для формирования вычисляемого
    # поля same_tags, которое содержит определенное количество совпадаю-
    # щих тегов;
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags', '-publish')[:4]
    # Django-taggit также включает менеджер similar_objects(), который мож-
    # но использовать для поиска подобных объектов. Ознакомиться с полным опи-
    # санием менеджеров django-taggit вы можете на странице
    # https://django-taggit.readthedocs.io/en/latest/api.html.
    return render(request, 'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


class PostListView(ListView):
    # queryset вместо model, чтобы использовать свой менеджер published
    queryset = Post.published.all()
    context_object_name = 'posts'  # иначе будет object_list
    paginate_by = 3  # ListView передает в контекст page_obj
    template_name = 'blog/post/list_cbv.html'


def post_share(request, post_id):
    # Получение статьи по идентификатору.
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False  # Отправлено ли сообщение, передаем в контекст
    if request.method == 'POST':
        # Форма была отправлена на сохранение.
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Все поля формы прошли валидацию.
            cd = form.cleaned_data
            # ... Отрпавка электронной почты.
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f'{cd["name"]} ({cd["email"]}) recommends you reading ' \
                f'"{post.title}"'
            message = f'Read "{post.title}" at {post_url}\n\n{cd["name"]}\'s ' \
                f'comments: {cd["comments"]}'
            send_mail(subject, message, 'admin@localhost', [cd["to"]])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_search(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # Мы можем повысить значимость некоторых векторов, чтобы
            # совпадения по ним считались более релевантными, чем по
            # остальным. Например, можно на- строить поиск так, чтобы статьи с
            # совпадениями в заголовке были в большем приоритете перед статьями
            # с совпадениями в содержимом.
            # search_vector = SearchVector('title', 'body')
            search_vector = SearchVector('title', weight='A') + \
                            SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                # search=search_vector,
                # rank=SearchRank(search_vector, search_query))\
                # ПОиск с помощью триграмм
                similarity=TrigramSimilarity('title', query))\
                .filter(similarity__gte=0.3).order_by('-similarity')
                # .filter(rank__gte=0.3).order_by('-rank')
                # .filter(search=search_query).order_by('-rank')
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'query': query,
                                                     'results': results})


def post_search_simple(request):
    """ Поиск """
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.annotate(
                search=SearchVector('title', 'body'),)\
                .filter(search=query)
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'query': query,
                                                     'results': results})


def post_search_rank(request):
    """ Стемминг и ранжирование результатов """
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('title', 'body')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query))\
                .filter(search=search_query).order_by('-rank')
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'query': query,
                                                     'results': results})


def post_search_weight(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # Мы можем повысить значимость некоторых векторов, чтобы
            # совпадения по ним считались более релевантными, чем по
            # остальным. Например, можно на- строить поиск так, чтобы статьи с
            # совпадениями в заголовке были в большем приоритете перед статьями
            # с совпадениями в содержимом.
            search_vector = SearchVector('title', weight='A') + \
                            SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query))\
                .filter(rank__gte=0.3).order_by('-rank')
            # В этом примере мы применяем векторы по полям title и body с
            # разным ве- сом. По умолчанию используются веса D, C, B и A,
            # которые соответствуют числам 0.1, 0.2, 0.4 и 1. Мы применили
            # вес 1.0 для вектора по полю title и 0.4 – для век- тора по полю
            # body. В конце отбрасываем статьи с низким рангом и показываем
            # только те, чей ранг выше 0.3.
    return render(request, 'blog/post/search.html', {'form': form,
                                                     'query': query,
                                                     'results': results})


def post_search_trigram_similarity(request):
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            results = Post.objects.annotate(
                similarity=TrigramSimilarity('title', query))\

blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">Share this post</a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </p>
    {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>{{ total_comments }} comment{{ total_comments|pluralize }}</h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {%  endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}

{% load blog_tags %}

{% block title %}My blog{% endblock %}
{% block content %}
    <h1>My blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
{#        <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>#}
        <p class="tags">Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|markdown|truncatewords:30 }}
    {% endfor %}

    {% include 'pagination.html' with page=posts %}

{% endblock %}

blog/templates/blog/post/list_cbv.html
{% extends 'blog/base.html' %}

{% load blog_tags %}


{% block title %}My blog{% endblock %}
{% block content %}
    <h1>My blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h2>
{#        <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>#}
        <p class="tags">Tags:
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
            {% endfor %}
        </p>
        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}

    {% include 'pagination.html' with page=page_obj %}
{% endblock %}

blog/templates/blog/post/search.html
{% extends 'blog/base.html' %}

{% block title %}Search{% endblock %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result {{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h4>
            {{ post.body|truncatewords:5 }}
        {% empty %}
            <p>There are no results for your query</p>
        {% endfor %}
        <p>
            <a href="{% url 'blog:post_search' %}">Search again</a>
        </p>
    {% else %}
        <h1>Search for posts</h1>
        <form action="." method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock %}

blog/templates/blog/post/share.html
{% extends 'blog/base.html' %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>

        <h2>Form as p</h2>
        <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>

        <h2>Iteration every field in form</h2>
        <form action="." method="post">
            {% csrf_token %}
            {% for field in form %}
                <div>
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                </div>
            {%  endfor %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}